#! /bin/cat
# https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02

# Simplified posix shell grammar for the minishell project

complete_command : list
                 ;
list             : and_or
                 ;
and_or           : pipeline
                 | pipeline TOK_AND and_or 
                 | pipeline TOK_OR and_or 
                 ;
pipeline         : pipe_sequence
                 ;
pipe_sequence    : command
                 | command TOK_PIPE pipe_sequence
                 ;
command          : simple_command
                 | compound_command
                 | compound_command redirect_list
                 ;
compound_command : subshell
                 ;
subshell         : TOK_L_PAREN compound_list TOK_R_PAREN
                 ;
compound_list    : term
                 ;
term             : and_or
                 ;
simple_command   : cmd_prefix cmd_word cmd_suffix
                 | cmd_prefix cmd_word
                 | cmd_prefix
                 | cmd_name cmd_suffix
                 | cmd_name
                 ;
cmd_name         : TOK_WORD
                 ;
cmd_word         : TOK_WORD
                 ;
cmd_prefix       : io_redirect
                 | io_redirect cmd_prefix
                 ;
cmd_suffix       : io_redirect
                 | io_redirect cmd_prefix
                 ;
redirect_list    : io_redirect
                 | io_redirect redirect_list
                 ;
io_redirect      : io_file
                 | io_here
                 ;
io_file          : TOK_APPEND   filename
                 | TOK_OVERRIDE filename
                 | TOK_INPUT    filename
                 ;
filename         : TOK_WORD
                 ;
io_here          : TOK_HEREDOC here_end
                 ;
here_end         : WORD
                 ;
